# Required plugins to run a sequencer node
plugins=["ZkTrieLogPlugin","BesuShomeiRpcPlugin"]

# TODO Other shomei options...
# Options required to run a shomei node
# ...
# TODO Other sequencer options...