services:
  linea-besu-advanced-mainnet-node:
    platform: linux/amd64
    image: consensys/linea-besu-package:latest
    command: --profile=advanced-mainnet --p2p-host=77.222.1.78 --plugin-linea-l1-rpc-endpoint=http://localhost:8545
    ports:
      - 30303:30303
      - 8545:8545
      - 8546:8546