# Chain
genesis-file="genesis/genesis.testnet-sepolia.json" # Path to the custom genesis file

# Required plugins to run a sequencer node
plugins=["LineaExtraDataPlugin","LineaEndpointServicePlugin","LineaTransactionPoolValidatorPlugin","LineaTransactionSelectorPlugin"]

# TODO Other sequencer options...
