name: Build Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ['devnet', 'sepolia', 'mainnet']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER_RW }}
          password: ${{ secrets.DOCKER_PAT_RW }}

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files: |
            linea-besu/build-*.json

      - name: Define Artifact Versions
        id: artifact-versions
        run: |
          CONFIG_FILE="linea-besu/build-${{ matrix.environment }}.json"
          linea_besu_version=$(jq -r '.modules[] | select(.name=="linea-besu") | .version' "$CONFIG_FILE")
          linea_sequencer_version=$(jq -r '.modules[] | select(.name=="linea-sequencer") | .version' "$CONFIG_FILE")
          finalized_tag_updater_version=$(jq -r '.modules[] | select(.name=="finalized-tag-updater") | .version' "$CONFIG_FILE")
      
          echo "linea_besu_version=$linea_besu_version" >> $GITHUB_ENV
          echo "linea_sequencer_version=$linea_sequencer_version" >> $GITHUB_ENV
          echo "finalized_tag_updater_version=$finalized_tag_updater_version" >> $GITHUB_ENV
    
      - name: download and untar the linea-besu archive
        run: |
          cd /tmp/
          echo "downloading linea-besu: ${{ env.linea_besu_version }}"
          wget -nv "https://artifacts.consensys.net/public/linea-besu/raw/names/linea-besu.tar.gz/versions/${{ env.linea_besu_version }}/linea-besu-${{ env.linea_besu_version }}.tar.gz"
          tar -xvf linea-besu-${{ env.linea_besu_version }}.tar.gz
          mv /tmp/linea-besu-${{ env.linea_besu_version }} /opt/besu
          
      - name: Build and push Docker image
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: |
            linea-besu-package:${{ matrix.environment }}-${{ env.linea_besu_version }}-${{ env.linea_sequencer_version }}-${{ env.finalized_tag_updater_version }}