name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create_release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Get VERSION output
        id: get_version
        run: echo "VERSION=${{ github.ref_name }}" >> $GITHUB_OUTPUT

      - name: Generate release body
        id: generate_body
        run: |
          config=$(cat linea-besu/build.json)
          
          body=$(echo "$config" | jq -r '.modules[] | "- **\(.name)**: \(.version // "[source](\(.src))")"')
         
          # Replace newlines with %0A for GitHub Actions output
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"
          
          echo "::set-output name=body::$body"

      - name: Build without tests
        run: ./gradlew build -PreleaseVersion=${{ steps.get_version.outputs.VERSION }}
        env:
          JAVA_OPTS: -Xmx2g -Dorg.gradle.daemon=false

      - name: Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.generate_body.outputs.body }}
          draft: true
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/linea-besu-package-${{ steps.get_version.outputs.VERSION }}.tar.gz
          asset_name: linea-besu-package-${{ steps.get_version.outputs.VERSION }}.tar.gz
          asset_content_type: application/octet-stream
