name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  create_release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Get VERSION output
        id: get_version
        run: echo "VERSION=${{ github.ref_name }}" >> $GITHUB_OUTPUT

      - name: Generate release body
        id: generate_body
        run: |
          config=$(cat linea-besu/build.json)
          
          body=$(echo "$config" | jq -r '.modules[] | "- **\(.name)**: \(.version // "[source](\(.src))")"')
         
          # Replace newlines with %0A for GitHub Actions output
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"
          
          echo "::set-output name=body::$body"

      - name: Build without tests
        run: ./gradlew build -PreleaseVersion=${{ steps.get_version.outputs.VERSION }}
        env:
          JAVA_OPTS: -Xmx2g -Dorg.gradle.daemon=false

      - name: Draft Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.generate_body.outputs.body }}
          generate_release_notes: true
          fail_on_unmatched_files: true
          draft: true
          files: |
            ./build/linea-besu-package-${{ steps.get_version.outputs.VERSION }}.tar.gz