name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  create_release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Get VERSION output
        id: get_version
        run: echo "VERSION=${{ github.ref_name }}" >> $GITHUB_OUTPUT

      - name: Build without tests
        run: ./gradlew build -PreleaseVersion=${{ steps.get_version.outputs.VERSION }}
        env:
          JAVA_OPTS: -Xmx2g -Dorg.gradle.daemon=false

      - name: Generate Release body
        id: generate_body
        run: |
          config=$(cat linea-besu/build.json)
          echo "## Release Notes for Version ${{ steps.get_version.outputs.VERSION }}" > output.md
          echo "" >> output.md
          echo "| Module | Version |" >> output.md
          echo "|--------|---------|" >> output.md
          echo "$config" | jq -r '.modules[] | select(.src == null) | "| **\(.name)** | \(.version // "[source](\(.url))") |"' >> output.md

      - name: Draft Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: output.md
          generate_release_notes: true
          fail_on_unmatched_files: true
          draft: true
          files: |
            ./build/linea-besu-package-${{ steps.get_version.outputs.VERSION }}.tar.gz